// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarFieldDefinition merges declarations of FieldDefinition that share the same FieldDefinition value.
// This uses the default basic merge strategy.
func SimilarFieldDefinition(curr []*ast.FieldDefinition, more ...*ast.FieldDefinition) ([]*ast.FieldDefinition, error) {
	return Basic.SimilarFieldDefinition(curr, more...)
}

// OneFieldDefinition attempts to merge all members of FieldDefinition into a singe *ast.FieldDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneFieldDefinition(curr []*ast.FieldDefinition, more ...*ast.FieldDefinition) (*ast.FieldDefinition, error) {
	return Basic.OneFieldDefinition(curr, more...)
}

// SimilarFieldDefinition merges declarations of FieldDefinition that share the same FieldDefinition value.
func (m *Merger) SimilarFieldDefinition(curr []*ast.FieldDefinition, more ...*ast.FieldDefinition) ([]*ast.FieldDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.FieldDefinition)
	for _, one := range all {
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.FieldDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneFieldDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneFieldDefinition attempts to merge all members of FieldDefinition into a singe *ast.FieldDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneFieldDefinition(curr []*ast.FieldDefinition, more ...*ast.FieldDefinition) (*ast.FieldDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	var listDescription []*ast.StringValue
	var listArguments []*ast.InputValueDefinition
	var listType []ast.Type
	var listDirectives []*ast.Directive
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
		listDescription = append(listDescription, one.Description)
		listArguments = append(listArguments, one.Arguments...)
		listType = append(listType, one.Type)
		listDirectives = append(listDirectives, one.Directives...)
	}

	var errSet error

	// merge properties

	one := ast.NewFieldDefinition(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.OneStringValue(listDescription); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Description = merged
	}
	if merged, err := m.SimilarInputValueDefinition(listArguments); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Arguments = merged
	}
	if merged, err := m.OneType(listType); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Type = merged
	}
	if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}

	return one, errSet

}
