// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarDirectiveDefinition merges declarations of DirectiveDefinition that share the same DirectiveDefinition value.
// This uses the default basic merge strategy.
func SimilarDirectiveDefinition(curr []*ast.DirectiveDefinition, more ...*ast.DirectiveDefinition) ([]*ast.DirectiveDefinition, error) {
	return Basic.SimilarDirectiveDefinition(curr, more...)
}

// OneDirectiveDefinition attempts to merge all members of DirectiveDefinition into a singe *ast.DirectiveDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneDirectiveDefinition(curr []*ast.DirectiveDefinition, more ...*ast.DirectiveDefinition) (*ast.DirectiveDefinition, error) {
	return Basic.OneDirectiveDefinition(curr, more...)
}

// SimilarDirectiveDefinition merges declarations of DirectiveDefinition that share the same DirectiveDefinition value.
func (m *Merger) SimilarDirectiveDefinition(curr []*ast.DirectiveDefinition, more ...*ast.DirectiveDefinition) ([]*ast.DirectiveDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.DirectiveDefinition)
	for _, one := range all {
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.DirectiveDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneDirectiveDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneDirectiveDefinition attempts to merge all members of DirectiveDefinition into a singe *ast.DirectiveDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneDirectiveDefinition(curr []*ast.DirectiveDefinition, more ...*ast.DirectiveDefinition) (*ast.DirectiveDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	var listDescription []*ast.StringValue
	var listArguments []*ast.InputValueDefinition
	var listLocations []*ast.Name
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
		listDescription = append(listDescription, one.Description)
		listArguments = append(listArguments, one.Arguments...)
		listLocations = append(listLocations, one.Locations...)
	}

	var errSet error

	// merge properties

	one := ast.NewDirectiveDefinition(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.OneStringValue(listDescription); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Description = merged
	}
	if merged, err := m.SimilarInputValueDefinition(listArguments); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Arguments = merged
	}
	if merged, err := m.SimilarName(listLocations); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Locations = merged
	}

	return one, errSet

}
