// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarOperationTypeDefinition merges declarations of OperationTypeDefinition that share the same OperationTypeDefinition value.
func (m *Merger) SimilarOperationTypeDefinition(curr []*ast.OperationTypeDefinition, more ...*ast.OperationTypeDefinition) ([]*ast.OperationTypeDefinition, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.OperationTypeDefinition)
	for _, one := range all {
		