// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarOperationTypeDefinition merges declarations of OperationTypeDefinition that share the same OperationTypeDefinition value.
// This uses the default basic merge strategy.
func SimilarOperationTypeDefinition(curr []*ast.OperationTypeDefinition, more ...*ast.OperationTypeDefinition) ([]*ast.OperationTypeDefinition, error) {
	return Basic.SimilarOperationTypeDefinition(curr, more...)
}

// OneOperationTypeDefinition attempts to merge all members of OperationTypeDefinition into a singe *ast.OperationTypeDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneOperationTypeDefinition(curr []*ast.OperationTypeDefinition, more ...*ast.OperationTypeDefinition) (*ast.OperationTypeDefinition, error) {
	return Basic.OneOperationTypeDefinition(curr, more...)
}

// SimilarOperationTypeDefinition merges declarations of OperationTypeDefinition that share the same OperationTypeDefinition value.
func (m *Merger) SimilarOperationTypeDefinition(curr []*ast.OperationTypeDefinition, more ...*ast.OperationTypeDefinition) ([]*ast.OperationTypeDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.OperationTypeDefinition)
	for _, one := range all {
		if key := m.getNodeID(one); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.OperationTypeDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneOperationTypeDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneOperationTypeDefinition attempts to merge all members of OperationTypeDefinition into a singe *ast.OperationTypeDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneOperationTypeDefinition(curr []*ast.OperationTypeDefinition, more ...*ast.OperationTypeDefinition) (*ast.OperationTypeDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listOperation []string
	var listType []*ast.Named
	// range over the parent struct and collect properties
	for _, one := range all {
		listOperation = append(listOperation, one.Operation)
		listType = append(listType, one.Type)
	}

	var errSet error

	// merge properties

	one := ast.NewOperationTypeDefinition(nil)
	if merged, err := m.Onestring(listOperation); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Operation = merged
	}
	if merged, err := m.OneNamed(listType); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Type = merged
	}

	return one, errSet

}
