// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarOperationDefinition merges declarations of OperationDefinition that share the same OperationDefinition value.
// This uses the default basic merge strategy.
func SimilarOperationDefinition(curr []*ast.OperationDefinition, more ...*ast.OperationDefinition) ([]*ast.OperationDefinition, error) {
	return Basic.SimilarOperationDefinition(curr, more...)
}

// OneOperationDefinition attempts to merge all members of OperationDefinition into a singe *ast.OperationDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneOperationDefinition(curr []*ast.OperationDefinition, more ...*ast.OperationDefinition) (*ast.OperationDefinition, error) {
	return Basic.OneOperationDefinition(curr, more...)
}

// SimilarOperationDefinition merges declarations of OperationDefinition that share the same OperationDefinition value.
func (m *Merger) SimilarOperationDefinition(curr []*ast.OperationDefinition, more ...*ast.OperationDefinition) ([]*ast.OperationDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.OperationDefinition)
	for _, one := range all {
		if one == nil {
			continue
		}
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.OperationDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneOperationDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneOperationDefinition attempts to merge all members of OperationDefinition into a singe *ast.OperationDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneOperationDefinition(curr []*ast.OperationDefinition, more ...*ast.OperationDefinition) (*ast.OperationDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listOperation []string
	var listName []*ast.Name
	var listVariableDefinitions []*ast.VariableDefinition
	var listDirectives []*ast.Directive
	var listSelectionSet []*ast.SelectionSet
	// range over the parent struct and collect properties
	for _, one := range all {
		listOperation = append(listOperation, one.Operation)
		listName = append(listName, one.Name)
		listVariableDefinitions = append(listVariableDefinitions, one.VariableDefinitions...)
		listDirectives = append(listDirectives, one.Directives...)
		listSelectionSet = append(listSelectionSet, one.SelectionSet)
	}

	var errSet error

	// merge properties

	one := ast.NewOperationDefinition(nil)
	if merged, err := m.Onestring(listOperation); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Operation = merged
	}
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.SimilarVariableDefinition(listVariableDefinitions); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.VariableDefinitions = merged
	}
	if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}
	if merged, err := m.OneSelectionSet(listSelectionSet); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.SelectionSet = merged
	}

	return one, errSet

}
