// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarObjectField merges declarations of ObjectField that share the same ObjectField value.
// This uses the default basic merge strategy.
func SimilarObjectField(curr []*ast.ObjectField, more ...*ast.ObjectField) ([]*ast.ObjectField, error) {
	return Basic.SimilarObjectField(curr, more...)
}

// OneObjectField attempts to merge all members of ObjectField into a singe *ast.ObjectField.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneObjectField(curr []*ast.ObjectField, more ...*ast.ObjectField) (*ast.ObjectField, error) {
	return Basic.OneObjectField(curr, more...)
}

// SimilarObjectField merges declarations of ObjectField that share the same ObjectField value.
func (m *Merger) SimilarObjectField(curr []*ast.ObjectField, more ...*ast.ObjectField) ([]*ast.ObjectField, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.ObjectField)
	for _, one := range all {
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.ObjectField
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneObjectField(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneObjectField attempts to merge all members of ObjectField into a singe *ast.ObjectField.
// If this cannot be done, this method will return an error.
func (m *Merger) OneObjectField(curr []*ast.ObjectField, more ...*ast.ObjectField) (*ast.ObjectField, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	var listValue []ast.Value
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
		listValue = append(listValue, one.Value)
	}

	var errSet error

	// merge properties

	one := ast.NewObjectField(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.OneValue(listValue); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Value = merged
	}

	return one, errSet

}
