// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarBooleanValue merges declarations of BooleanValue that share the same BooleanValue value.
func (m *Merger) SimilarBooleanValue(curr []*ast.BooleanValue, more ...*ast.BooleanValue) ([]*ast.BooleanValue, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.BooleanValue)
	for _, one := range all {
		