// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarValue merges declarations of Value that share the same Value value.
func (m *Merger) SimilarValue(curr []ast.Value, more ...ast.Value) ([]ast.Value, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]ast.Value)
	for _, one := range all {
		name := m.getValueID(one)
		if name != "" {
			curr, _ := groups[name]
			groups[name] = append(curr, one)
		}
	}

	var out []ast.Value
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneValue(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneValue attempts to merge all members of Value into a singe ast.Value.
// If this cannot be done, this method will return an error.
func (m *Merger) OneValue(curr []ast.Value, more ...ast.Value) (ast.Value, error) {
	// step 1 - escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}

	// step 2 - prepare property collections (if any)


	// step 3 - range over the parent struct and collect properties

	// step 4 - prepare output types
	one := ast.NewValue(nil)
	var errSet error

	// step 5 - merge properties


	return one, errSet
}
