// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarBooleanValue merges declarations of BooleanValue that share the same BooleanValue value.
func (m *Merger) SimilarBooleanValue(curr []*ast.BooleanValue, more ...*ast.BooleanValue) ([]*ast.BooleanValue, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.BooleanValue)
	for _, one := range all {
		name := m.getValueID(one)
		if name != "" {
			curr, _ := groups[name]
			groups[name] = append(curr, one)
		}
	}

	var out []*ast.BooleanValue
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneBooleanValue(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneBooleanValue attempts to merge all members of BooleanValue into a singe *ast.BooleanValue.
// If this cannot be done, this method will return an error.
func (m *Merger) OneBooleanValue(curr []*ast.BooleanValue, more ...*ast.BooleanValue) (*ast.BooleanValue, error) {
	// step 1 - escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}

	// step 2 - prepare property collections (if any)

	// step 3 - range over the parent struct and collect properties
	for _, one := range all {
		// 3.a - prevent empty loop from making syntax errors
		_ = one

		// 3.b - accrue properties
	}

	// step 4 - prepare output types
	one := ast.NewBooleanValue(nil)
	var errSet error

	// step 5 - merge properties

	return one, errSet
}
