// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarInputObjectDefinition merges declarations of InputObjectDefinition that share the same InputObjectDefinition value.
// This uses the default basic merge strategy.
func SimilarInputObjectDefinition(curr []*ast.InputObjectDefinition, more ...*ast.InputObjectDefinition) ([]*ast.InputObjectDefinition, error) {
	return Basic.SimilarInputObjectDefinition(curr, more...)
}

// OneInputObjectDefinition attempts to merge all members of InputObjectDefinition into a singe *ast.InputObjectDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneInputObjectDefinition(curr []*ast.InputObjectDefinition, more ...*ast.InputObjectDefinition) (*ast.InputObjectDefinition, error) {
	return Basic.OneInputObjectDefinition(curr, more...)
}

// SimilarInputObjectDefinition merges declarations of InputObjectDefinition that share the same InputObjectDefinition value.
func (m *Merger) SimilarInputObjectDefinition(curr []*ast.InputObjectDefinition, more ...*ast.InputObjectDefinition) ([]*ast.InputObjectDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.InputObjectDefinition)
	for _, one := range all {
		if one == nil {
			continue
		}
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.InputObjectDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneInputObjectDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneInputObjectDefinition attempts to merge all members of InputObjectDefinition into a singe *ast.InputObjectDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneInputObjectDefinition(curr []*ast.InputObjectDefinition, more ...*ast.InputObjectDefinition) (*ast.InputObjectDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	var listDescription []*ast.StringValue
	var listDirectives []*ast.Directive
	var listFields []*ast.InputValueDefinition
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
		listDescription = append(listDescription, one.Description)
		listDirectives = append(listDirectives, one.Directives...)
		listFields = append(listFields, one.Fields...)
	}

	var errSet error

	// merge properties

	one := ast.NewInputObjectDefinition(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.OneStringValue(listDescription); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Description = merged
	}
	if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}
	if merged, err := m.SimilarInputValueDefinition(listFields); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Fields = merged
	}

	return one, errSet

}
