// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarScalarDefinition merges declarations of ScalarDefinition that share the same ScalarDefinition value.
func (m *Merger) SimilarScalarDefinition(curr []*ast.ScalarDefinition, more ...*ast.ScalarDefinition) ([]*ast.ScalarDefinition, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.ScalarDefinition)
	for _, one := range all {
		name := fmt.Sprint(printer.Print(one.Name))
		if name != "" {
			curr, _ := groups[name]
			groups[name] = append(curr, one)
		}
	}

	var out []*ast.ScalarDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneScalarDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneScalarDefinition attempts to merge all members of ScalarDefinition into a singe *ast.ScalarDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneScalarDefinition(curr []*ast.ScalarDefinition, more ...*ast.ScalarDefinition) (*ast.ScalarDefinition, error) {
	// step 1 - escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}

	// step 2 - prepare property collections (if any)
  var listDescription []*ast.StringValue
  var listName []*ast.Name
  var listDirectives []*ast.Directive

	// step 3 - range over the parent struct and collect properties
	for _, one := range all {
    listDescription = append(listDescription, one.Description)
    listName = append(listName, one.Name)
    listDirectives = append(listDirectives, one.Directives...)
	}

	// step 4 - prepare output types
	one := ast.NewScalarDefinition(nil)
	var errSet error

	// step 5 - merge properties
  if merged, err := m.OneStringValue(listDescription); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Description = merged
	}
  if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
  if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}

	return one, errSet
}
