// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarDirective merges declarations of Directive that share the same Directive value.
func (m *Merger) SimilarDirective(curr []*ast.Directive, more ...*ast.Directive) ([]*ast.Directive, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.Directive)
	for _, one := range all {
		name := fmt.Sprint(printer.Print(one.Name))
		if name != "" {
			curr, _ := groups[name]
			groups[name] = append(curr, one)
		}
	}

	var out []*ast.Directive
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneDirective(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneDirective attempts to merge all members of Directive into a singe *ast.Directive.
// If this cannot be done, this method will return an error.
func (m *Merger) OneDirective(curr []*ast.Directive, more ...*ast.Directive) (*ast.Directive, error) {
	// step 1 - escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}

	// step 2 - prepare property collections (if any)
  var listName []*ast.Name
  var listArguments []*ast.Argument

	// step 3 - range over the parent struct and collect properties
	for _, one := range all {
    listName = append(listName, one.Name)
    listArguments = append(listArguments, one.Arguments...)
	}

	// step 4 - prepare output types
	one := ast.NewDirective(nil)
	var errSet error

	// step 5 - merge properties
  if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
  if merged, err := m.SimilarArgument(listArguments); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Arguments = merged
	}

	return one, errSet
}
