// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarSchemaDefinition merges declarations of SchemaDefinition that share the same SchemaDefinition value.
// This uses the default basic merge strategy.
func SimilarSchemaDefinition(curr []*ast.SchemaDefinition, more ...*ast.SchemaDefinition) ([]*ast.SchemaDefinition, error) {
	return Basic.SimilarSchemaDefinition(curr, more...)
}

// OneSchemaDefinition attempts to merge all members of SchemaDefinition into a singe *ast.SchemaDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneSchemaDefinition(curr []*ast.SchemaDefinition, more ...*ast.SchemaDefinition) (*ast.SchemaDefinition, error) {
	return Basic.OneSchemaDefinition(curr, more...)
}

// SimilarSchemaDefinition merges declarations of SchemaDefinition that share the same SchemaDefinition value.
func (m *Merger) SimilarSchemaDefinition(curr []*ast.SchemaDefinition, more ...*ast.SchemaDefinition) ([]*ast.SchemaDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.SchemaDefinition)
	for _, one := range all {
		if one == nil {
			continue
		}
		if key := m.getNodeID(one); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.SchemaDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneSchemaDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneSchemaDefinition attempts to merge all members of SchemaDefinition into a singe *ast.SchemaDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneSchemaDefinition(curr []*ast.SchemaDefinition, more ...*ast.SchemaDefinition) (*ast.SchemaDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listDirectives []*ast.Directive
	var listOperationTypes []*ast.OperationTypeDefinition
	// range over the parent struct and collect properties
	for _, one := range all {
		listDirectives = append(listDirectives, one.Directives...)
		listOperationTypes = append(listOperationTypes, one.OperationTypes...)
	}

	var errSet error

	// merge properties

	one := ast.NewSchemaDefinition(nil)
	if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}
	if merged, err := m.SimilarOperationTypeDefinition(listOperationTypes); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.OperationTypes = merged
	}

	return one, errSet

}
