// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarSelectionSet merges declarations of SelectionSet that share the same SelectionSet value.
// This uses the default basic merge strategy.
func SimilarSelectionSet(curr []*ast.SelectionSet, more ...*ast.SelectionSet) ([]*ast.SelectionSet, error) {
	return Basic.SimilarSelectionSet(curr, more...)
}

// OneSelectionSet attempts to merge all members of SelectionSet into a singe *ast.SelectionSet.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneSelectionSet(curr []*ast.SelectionSet, more ...*ast.SelectionSet) (*ast.SelectionSet, error) {
	return Basic.OneSelectionSet(curr, more...)
}

// SimilarSelectionSet merges declarations of SelectionSet that share the same SelectionSet value.
func (m *Merger) SimilarSelectionSet(curr []*ast.SelectionSet, more ...*ast.SelectionSet) ([]*ast.SelectionSet, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.SelectionSet)
	for _, one := range all {
		if one == nil {
			continue
		}
		if key := m.getNodeID(one); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.SelectionSet
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneSelectionSet(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneSelectionSet attempts to merge all members of SelectionSet into a singe *ast.SelectionSet.
// If this cannot be done, this method will return an error.
func (m *Merger) OneSelectionSet(curr []*ast.SelectionSet, more ...*ast.SelectionSet) (*ast.SelectionSet, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listSelections []ast.Selection
	// range over the parent struct and collect properties
	for _, one := range all {
		listSelections = append(listSelections, one.Selections...)
	}

	var errSet error

	// merge properties

	one := ast.NewSelectionSet(nil)
	if merged, err := m.SimilarSelection(listSelections); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Selections = merged
	}

	return one, errSet

}
