// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarNonNull merges declarations of NonNull that share the same NonNull value.
// This uses the default basic merge strategy.
func SimilarNonNull(curr []*ast.NonNull, more ...*ast.NonNull) ([]*ast.NonNull, error) {
	return Basic.SimilarNonNull(curr, more...)
}

// OneNonNull attempts to merge all members of NonNull into a singe *ast.NonNull.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneNonNull(curr []*ast.NonNull, more ...*ast.NonNull) (*ast.NonNull, error) {
	return Basic.OneNonNull(curr, more...)
}

// SimilarNonNull merges declarations of NonNull that share the same NonNull value.
func (m *Merger) SimilarNonNull(curr []*ast.NonNull, more ...*ast.NonNull) ([]*ast.NonNull, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.NonNull)
	for _, one := range all {
		if key := m.getNodeID(one); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.NonNull
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneNonNull(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneNonNull attempts to merge all members of NonNull into a singe *ast.NonNull.
// If this cannot be done, this method will return an error.
func (m *Merger) OneNonNull(curr []*ast.NonNull, more ...*ast.NonNull) (*ast.NonNull, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listType []ast.Type
	// range over the parent struct and collect properties
	for _, one := range all {
		listType = append(listType, one.Type)
	}

	var errSet error

	// merge properties

	one := ast.NewNonNull(nil)
	if merged, err := m.OneType(listType); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Type = merged
	}

	return one, errSet

}
