// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarBooleanValue merges declarations of BooleanValue that share the same BooleanValue value.
// This uses the default basic merge strategy.
func SimilarBooleanValue(curr []*ast.BooleanValue, more ...*ast.BooleanValue) ([]*ast.BooleanValue, error) {
	return Basic.SimilarBooleanValue(curr, more...)
}

// OneBooleanValue attempts to merge all members of BooleanValue into a singe *ast.BooleanValue.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneBooleanValue(curr []*ast.BooleanValue, more ...*ast.BooleanValue) (*ast.BooleanValue, error) {
	return Basic.OneBooleanValue(curr, more...)
}

// SimilarBooleanValue merges declarations of BooleanValue that share the same BooleanValue value.
func (m *Merger) SimilarBooleanValue(curr []*ast.BooleanValue, more ...*ast.BooleanValue) ([]*ast.BooleanValue, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.BooleanValue)
	for _, one := range all {
		if key := m.getNodeID(one); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.BooleanValue
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneBooleanValue(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneBooleanValue attempts to merge all members of BooleanValue into a singe *ast.BooleanValue.
// If this cannot be done, this method will return an error.
func (m *Merger) OneBooleanValue(curr []*ast.BooleanValue, more ...*ast.BooleanValue) (*ast.BooleanValue, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listValue []bool
	// range over the parent struct and collect properties
	for _, one := range all {
		listValue = append(listValue, one.Value)
	}

	var errSet error

	// merge properties

	one := ast.NewBooleanValue(nil)
	if merged, err := m.Onebool(listValue); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Value = merged
	}

	return one, errSet

}
