// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarUnionDefinition merges declarations of UnionDefinition that share the same UnionDefinition value.
// This uses the default basic merge strategy.
func SimilarUnionDefinition(curr []*ast.UnionDefinition, more ...*ast.UnionDefinition) ([]*ast.UnionDefinition, error) {
	return Basic.SimilarUnionDefinition(curr, more...)
}

// OneUnionDefinition attempts to merge all members of UnionDefinition into a singe *ast.UnionDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneUnionDefinition(curr []*ast.UnionDefinition, more ...*ast.UnionDefinition) (*ast.UnionDefinition, error) {
	return Basic.OneUnionDefinition(curr, more...)
}

// SimilarUnionDefinition merges declarations of UnionDefinition that share the same UnionDefinition value.
func (m *Merger) SimilarUnionDefinition(curr []*ast.UnionDefinition, more ...*ast.UnionDefinition) ([]*ast.UnionDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.UnionDefinition)
	for _, one := range all {
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.UnionDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneUnionDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneUnionDefinition attempts to merge all members of UnionDefinition into a singe *ast.UnionDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneUnionDefinition(curr []*ast.UnionDefinition, more ...*ast.UnionDefinition) (*ast.UnionDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	var listDescription []*ast.StringValue
	var listDirectives []*ast.Directive
	var listTypes []*ast.Named
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
		listDescription = append(listDescription, one.Description)
		listDirectives = append(listDirectives, one.Directives...)
		listTypes = append(listTypes, one.Types...)
	}

	var errSet error

	// merge properties

	one := ast.NewUnionDefinition(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.OneStringValue(listDescription); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Description = merged
	}
	if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}
	if merged, err := m.SimilarNamed(listTypes); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Types = merged
	}

	return one, errSet

}
