// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarNonNull merges declarations of NonNull that share the same NonNull value.
func (m *Merger) SimilarNonNull(curr []*ast.NonNull, more ...*ast.NonNull) ([]*ast.NonNull, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.NonNull)
	for _, one := range all {
		name := m.getValueID(one)
		if name != "" {
			curr, _ := groups[name]
			groups[name] = append(curr, one)
		}
	}

	var out []*ast.NonNull
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneNonNull(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneNonNull attempts to merge all members of NonNull into a singe *ast.NonNull.
// If this cannot be done, this method will return an error.
func (m *Merger) OneNonNull(curr []*ast.NonNull, more ...*ast.NonNull) (*ast.NonNull, error) {
	// step 1 - escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}

	// step 2 - prepare property collections (if any)
  var listType []ast.Type

	// step 3 - range over the parent struct and collect properties
	for _, one := range all {
    listType = append(listType, one.Type)
	}

	// step 4 - prepare output types
	one := ast.NewNonNull(nil)
	var errSet error

	// step 5 - merge properties
  if merged, err := m.OneType(listType); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Type = merged
	}

	return one, errSet
}
