// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarInterfaceDefinition merges declarations of InterfaceDefinition that share the same InterfaceDefinition value.
// This uses the default basic merge strategy.
func SimilarInterfaceDefinition(curr []*ast.InterfaceDefinition, more ...*ast.InterfaceDefinition) ([]*ast.InterfaceDefinition, error) {
	return Basic.SimilarInterfaceDefinition(curr, more...)
}

// OneInterfaceDefinition attempts to merge all members of InterfaceDefinition into a singe *ast.InterfaceDefinition.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneInterfaceDefinition(curr []*ast.InterfaceDefinition, more ...*ast.InterfaceDefinition) (*ast.InterfaceDefinition, error) {
	return Basic.OneInterfaceDefinition(curr, more...)
}

// SimilarInterfaceDefinition merges declarations of InterfaceDefinition that share the same InterfaceDefinition value.
func (m *Merger) SimilarInterfaceDefinition(curr []*ast.InterfaceDefinition, more ...*ast.InterfaceDefinition) ([]*ast.InterfaceDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.InterfaceDefinition)
	for _, one := range all {
		if one == nil {
			continue
		}
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.InterfaceDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneInterfaceDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneInterfaceDefinition attempts to merge all members of InterfaceDefinition into a singe *ast.InterfaceDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneInterfaceDefinition(curr []*ast.InterfaceDefinition, more ...*ast.InterfaceDefinition) (*ast.InterfaceDefinition, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	var listDescription []*ast.StringValue
	var listDirectives []*ast.Directive
	var listFields []*ast.FieldDefinition
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
		listDescription = append(listDescription, one.Description)
		listDirectives = append(listDirectives, one.Directives...)
		listFields = append(listFields, one.Fields...)
	}

	var errSet error

	// merge properties

	one := ast.NewInterfaceDefinition(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.OneStringValue(listDescription); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Description = merged
	}
	if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}
	if merged, err := m.SimilarFieldDefinition(listFields); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Fields = merged
	}

	return one, errSet

}
