// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarTypeExtensionDefinition merges declarations of TypeExtensionDefinition that share the same TypeExtensionDefinition value.
func (m *Merger) SimilarTypeExtensionDefinition(curr []*ast.TypeExtensionDefinition, more ...*ast.TypeExtensionDefinition) ([]*ast.TypeExtensionDefinition, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.TypeExtensionDefinition)
	for _, one := range all {
		name := fmt.Sprint(printer.Print(one.Definition.Name))
		if name != "" {
			curr, _ := groups[name]
			groups[name] = append(curr, one)
		}
	}

	var out []*ast.TypeExtensionDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneTypeExtensionDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneTypeExtensionDefinition attempts to merge all members of TypeExtensionDefinition into a singe *ast.TypeExtensionDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneTypeExtensionDefinition(curr []*ast.TypeExtensionDefinition, more ...*ast.TypeExtensionDefinition) (*ast.TypeExtensionDefinition, error) {
	// step 1 - escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}

	// step 2 - prepare property collections (if any)
  var listDefinition []*ast.ObjectDefinition

	// step 3 - range over the parent struct and collect properties
	for _, one := range all {
    listDefinition = append(listDefinition, one.Definition)
	}

	// step 4 - prepare output types
	one := ast.NewTypeExtensionDefinition(nil)
	var errSet error

	// step 5 - merge properties
  if merged, err := m.OneObjectDefinition(listDefinition); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Definition = merged
	}

	return one, errSet
}
