// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarObjectValue merges declarations of ObjectValue that share the same ObjectValue value.
// This uses the default basic merge strategy.
func SimilarObjectValue(curr []*ast.ObjectValue, more ...*ast.ObjectValue) ([]*ast.ObjectValue, error) {
	return Basic.SimilarObjectValue(curr, more...)
}

// OneObjectValue attempts to merge all members of ObjectValue into a singe *ast.ObjectValue.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneObjectValue(curr []*ast.ObjectValue, more ...*ast.ObjectValue) (*ast.ObjectValue, error) {
	return Basic.OneObjectValue(curr, more...)
}

// SimilarObjectValue merges declarations of ObjectValue that share the same ObjectValue value.
func (m *Merger) SimilarObjectValue(curr []*ast.ObjectValue, more ...*ast.ObjectValue) ([]*ast.ObjectValue, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.ObjectValue)
	for _, one := range all {
		if one == nil {
			continue
		}
		if key := m.getNodeID(one); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.ObjectValue
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneObjectValue(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneObjectValue attempts to merge all members of ObjectValue into a singe *ast.ObjectValue.
// If this cannot be done, this method will return an error.
func (m *Merger) OneObjectValue(curr []*ast.ObjectValue, more ...*ast.ObjectValue) (*ast.ObjectValue, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listFields []*ast.ObjectField
	// range over the parent struct and collect properties
	for _, one := range all {
		listFields = append(listFields, one.Fields...)
	}

	var errSet error

	// merge properties

	one := ast.NewObjectValue(nil)
	if merged, err := m.SimilarObjectField(listFields); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Fields = merged
	}

	return one, errSet

}
