// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarInputValueDefinition merges declarations of InputValueDefinition that share the same InputValueDefinition value.
func (m *Merger) SimilarInputValueDefinition(curr []*ast.InputValueDefinition, more ...*ast.InputValueDefinition) ([]*ast.InputValueDefinition, error) {
	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.InputValueDefinition)
	for _, one := range all {
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.InputValueDefinition
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneInputValueDefinition(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneInputValueDefinition attempts to merge all members of InputValueDefinition into a singe *ast.InputValueDefinition.
// If this cannot be done, this method will return an error.
func (m *Merger) OneInputValueDefinition(curr []*ast.InputValueDefinition, more ...*ast.InputValueDefinition) (*ast.InputValueDefinition, error) {
	// step 1 - escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	var listDescription []*ast.StringValue
	var listType []ast.Type
	var listDefaultValue []ast.Value
	var listDirectives []*ast.Directive
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
		listDescription = append(listDescription, one.Description)
		listType = append(listType, one.Type)
		listDefaultValue = append(listDefaultValue, one.DefaultValue)
		listDirectives = append(listDirectives, one.Directives...)
	}

	var errSet error

	// merge properties

	one := ast.NewInputValueDefinition(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}
	if merged, err := m.OneStringValue(listDescription); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Description = merged
	}
	if merged, err := m.OneType(listType); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Type = merged
	}
	if merged, err := m.OneValue(listDefaultValue); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.DefaultValue = merged
	}
	if merged, err := m.SimilarDirective(listDirectives); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Directives = merged
	}

	return one, errSet

}
