// Code generated by go generate; DO NOT EDIT.
package mergers

import (
	"fmt"
	"github.com/graphql-go/graphql/language/ast"
	"github.com/graphql-go/graphql/language/printer"
	"github.com/richardwilkes/toolbox/errs"
)

var _ = fmt.Sprint
var _ = printer.Print

// SimilarNamed merges declarations of Named that share the same Named value.
// This uses the default basic merge strategy.
func SimilarNamed(curr []*ast.Named, more ...*ast.Named) ([]*ast.Named, error) {
	return Basic.SimilarNamed(curr, more...)
}

// OneNamed attempts to merge all members of Named into a singe *ast.Named.
// If this cannot be done, this method will return an error.
// This uses the default basic merge strategy.
func OneNamed(curr []*ast.Named, more ...*ast.Named) (*ast.Named, error) {
	return Basic.OneNamed(curr, more...)
}

// SimilarNamed merges declarations of Named that share the same Named value.
func (m *Merger) SimilarNamed(curr []*ast.Named, more ...*ast.Named) ([]*ast.Named, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	all := append(curr, more...)
	if len(all) <= 1 {
		return all, nil
	}

	groups := make(map[string][]*ast.Named)
	for _, one := range all {
		if one == nil {
			continue
		}
		if key := fmt.Sprint(printer.Print(one.Name)); key != "" {
			curr, _ := groups[key]
			groups[key] = append(curr, one)
		}
	}

	var out []*ast.Named
	var errSet error

	for _, group := range groups {
		if merged, err := m.OneNamed(group); err != nil {
			errSet = errs.Append(errSet, err)
		} else if merged != nil {
			out = append(out, merged)
		}
	}

	return out, errSet
}

// OneNamed attempts to merge all members of Named into a singe *ast.Named.
// If this cannot be done, this method will return an error.
func (m *Merger) OneNamed(curr []*ast.Named, more ...*ast.Named) (*ast.Named, error) {
	if m == nil {
		return nil, errs.New("merger strategy was nil")
	}

	// escape hatch when no calculation is needed
	all := append(curr, more...)
	if n := len(all); n == 0 {
		return nil, nil
	} else if n == 1 {
		return all[0], nil
	}
	// prepare property collections
	var listName []*ast.Name
	// range over the parent struct and collect properties
	for _, one := range all {
		listName = append(listName, one.Name)
	}

	var errSet error

	// merge properties

	one := ast.NewNamed(nil)
	if merged, err := m.OneName(listName); err != nil {
		errSet = errs.Append(errSet, err)
	} else {
		one.Name = merged
	}

	return one, errSet

}
